export const cityData = [
  { key: 0, section: true, label: "시/도" },
  { key: 1, label: "서울특별시" },
  { key: 2, label: "부산광역시" },
  { key: 3, label: "대구광역시" },
  { key: 4, label: "인천광역시" },
  { key: 5, label: "광주광역시" },
  { key: 6, label: "대전광역시" },
  { key: 7, label: "울산광역시" },
  { key: 8, label: "세종특별자치시" },
  { key: 9, label: "경기도" },
  { key: 10, label: "강원도" },
  { key: 11, label: "충청북도" },
  { key: 12, label: "충청남도" },
  { key: 13, label: "전라북도" },
  { key: 14, label: "전라남도" },
  { key: 15, label: "경상북도" },
  { key: 16, label: "경상남도" },
  { key: 17, label: "제주특별자치도" }
];
export const streetData = [
  [
    { key: 0, section: true, label: "서울" },
    { key: 1, label: "강남구" },
    { key: 2, label: "강동구" },
    { key: 3, label: "강북구" },
    { key: 4, label: "강서구" },
    { key: 5, label: "관악구" },
    { key: 6, label: "광진구" },
    { key: 7, label: "구로구" },
    { key: 8, label: "금천구" },
    { key: 9, label: "노원구" },
    { key: 10, label: "도봉구" },
    { key: 11, label: "동대문구" },
    { key: 12, label: "동작구" },
    { key: 13, label: "마포구" },
    { key: 14, label: "서대문구" },
    { key: 15, label: "서초구" },
    { key: 16, label: "성동구" },
    { key: 17, label: "성북구" },
    { key: 18, label: "송파구" },
    { key: 19, label: "양천구" },
    { key: 20, label: "영등포구" },
    { key: 21, label: "용산구" },
    { key: 22, label: "은평구" },
    { key: 23, label: "종로구" },
    { key: 24, label: "중구" },
    { key: 25, label: "중랑구" }
  ],
  [
    { key: 0, section: true, label: "부산광역시" },
    { key: 1, label: "강서구" },
    { key: 2, label: "금정구" },
    { key: 3, label: "남구" },
    { key: 4, label: "동구" },
    { key: 5, label: "동래구" },
    { key: 6, label: "부산진구" },
    { key: 7, label: "북구" },
    { key: 8, label: "사상구" },
    { key: 9, label: "사하구" },
    { key: 10, label: "서구" },
    { key: 11, label: "수영구" },
    { key: 12, label: "연제구" },
    { key: 13, label: "영도구" },
    { key: 14, label: "중구" },
    { key: 15, label: "해운대구" },
    { key: 16, label: "기장군" }
  ],
  [
    { key: 0, section: true, label: "대구광역시" },
    { key: 1, label: "남구" },
    { key: 2, label: "달서구" },
    { key: 3, label: "동구" },
    { key: 4, label: "북구" },
    { key: 5, label: "서구" },
    { key: 6, label: "수성구" },
    { key: 7, label: "중구" },
    { key: 8, label: "달성군" }
  ],
  [
    { key: 0, section: true, label: "인천광역시" },
    { key: 1, label: "계양구" },
    { key: 2, label: "미추홀구" },
    { key: 3, label: "남동구" },
    { key: 4, label: "동구" },
    { key: 5, label: "부평구" },
    { key: 6, label: "서구" },
    { key: 7, label: "연수구" },
    { key: 8, label: "중구" },
    { key: 9, label: "강화군" },
    { key: 10, label: "옹진군" }
  ],
  [
    { key: 0, section: true, label: "광주광역시" },
    { key: 1, label: "광산구" },
    { key: 2, label: "남구" },
    { key: 3, label: "동구" },
    { key: 4, label: "북구" },
    { key: 5, label: "서구" }
  ],
  [
    { key: 0, section: true, label: "대전광역시" },
    { key: 1, label: "대덕구" },
    { key: 2, label: "동구" },
    { key: 3, label: "서구" },
    { key: 4, label: "유성구" },
    { key: 5, label: "중구" }
  ],
  [
    { key: 0, section: true, label: "울산광역시" },
    { key: 1, label: "남구" },
    { key: 2, label: "동구" },
    { key: 3, label: "북구" },
    { key: 4, label: "중구" },
    { key: 5, label: "울주군" }
  ],
  [{ key: 0, label: "세종특별자치시" }],
  [
    { key: 0, section: true, label: "경기도" },
    { key: 1, label: "고양시" },
    { key: 2, label: "과천시" },
    { key: 3, label: "광명시" },
    { key: 4, label: "광주시" },
    { key: 5, label: "구리시" },
    { key: 6, label: "군포시" },
    { key: 7, label: "김포시" },
    { key: 8, label: "남양주시" },
    { key: 9, label: "동두천시" },
    { key: 10, label: "부천시" },
    { key: 11, label: "성남시" },
    { key: 12, label: "수원시" },
    { key: 13, label: "시흥시" },
    { key: 14, label: "안산시" },
    { key: 15, label: "안성시" },
    { key: 16, label: "안양시" },
    { key: 17, label: "양주시" },
    { key: 18, label: "여주시" },
    { key: 19, label: "오산시" },
    { key: 20, label: "용인시" },
    { key: 21, label: "의왕시" },
    { key: 22, label: "의정부시" },
    { key: 23, label: "이천시" },
    { key: 24, label: "파주시" },
    { key: 25, label: "평택시" },
    { key: 26, label: "하남시" },
    { key: 27, label: "화성시" },
    { key: 28, label: "가평군" },
    { key: 29, label: "양평군" },
    { key: 30, label: "연천군" }
  ],
  [
    { key: 0, section: true, label: "강원도" },
    { key: 1, label: "강릉시" },
    { key: 2, label: "동해시" },
    { key: 3, label: "삼척시" },
    { key: 4, label: "속초시" },
    { key: 5, label: "원주시" },
    { key: 6, label: "춘천시" },
    { key: 7, label: "태백시" },
    { key: 8, label: "고성군" },
    { key: 9, label: "양구군" },
    { key: 10, label: "양양군" },
    { key: 11, label: "영월군" },
    { key: 12, label: "인제군" },
    { key: 13, label: "정선군" },
    { key: 14, label: "철원군" },
    { key: 15, label: "평창군" },
    { key: 16, label: "홍천군" },
    { key: 17, label: "화천군" },
    { key: 18, label: "횡성군" }
  ],
  [
    { key: 0, section: true, label: "충청북도" },
    { key: 1, label: "제천시" },
    { key: 2, label: "청주시" },
    { key: 3, label: "충주시" },
    { key: 4, label: "괴산군" },
    { key: 5, label: "단양군" },
    { key: 6, label: "보은군" },
    { key: 7, label: "영동군" },
    { key: 8, label: "옥천군" },
    { key: 9, label: "음성군" },
    { key: 10, label: "증평군" },
    { key: 11, label: "진천군" }
  ],
  [
    { key: 0, section: true, label: "충청남도" },
    { key: 1, label: "계룡시" },
    { key: 2, label: "공주시" },
    { key: 3, label: "논산시" },
    { key: 4, label: "당진시" },
    { key: 5, label: "보령시" },
    { key: 6, label: "서산시" },
    { key: 7, label: "아산시" },
    { key: 8, label: "천안시" },
    { key: 9, label: "금산군" },
    { key: 10, label: "부여군" },
    { key: 11, label: "서천군" },
    { key: 12, label: "예산군" },
    { key: 13, label: "청양군" },
    { key: 14, label: "태안군" },
    { key: 15, label: "홍성군" }
  ],
  [
    { key: 0, section: true, label: "전라북도" },
    { key: 1, label: "군산시" },
    { key: 2, label: "김제시" },
    { key: 3, label: "남원시" },
    { key: 4, label: "익산시" },
    { key: 5, label: "전주시" },
    { key: 6, label: "정읍시" },
    { key: 7, label: "고창군" },
    { key: 8, label: "무주군" },
    { key: 9, label: "부안군" },
    { key: 10, label: "순창군" },
    { key: 11, label: "완주군" },
    { key: 12, label: "임실군" },
    { key: 13, label: "장수군" },
    { key: 14, label: "진안군" }
  ],
  [
    { key: 0, section: true, label: "전라남도" },
    { key: 0, section: true, label: "광양시" },
    { key: 1, label: "나주시" },
    { key: 2, label: "목포시" },
    { key: 3, label: "순천시" },
    { key: 4, label: "여수시" },
    { key: 5, label: "강진군" },
    { key: 6, label: "고흥군" },
    { key: 7, label: "곡성군" },
    { key: 8, label: "구례군" },
    { key: 9, label: "담양군" },
    { key: 10, label: "무안군" },
    { key: 11, label: "보성군" },
    { key: 12, label: "신안군" },
    { key: 13, label: "영광군" },
    { key: 14, label: "영암군" },
    { key: 15, label: "완도군" },
    { key: 16, label: "장성군" },
    { key: 17, label: "장흥군" },
    { key: 18, label: "진도군" },
    { key: 19, label: "함평군" },
    { key: 20, label: "해남군" },
    { key: 21, label: "화순군" }
  ],
  [
    { key: 0, section: true, label: "경상북도" },
    { key: 1, label: "경산시" },
    { key: 2, label: "경주시" },
    { key: 3, label: "구미시" },
    { key: 4, label: "김천시" },
    { key: 5, label: "문경시" },
    { key: 6, label: "상주시" },
    { key: 7, label: "안동시" },
    { key: 8, label: "영주시" },
    { key: 9, label: "영천시" },
    { key: 10, label: "포항시" },
    { key: 11, label: "고령군" },
    { key: 12, label: "군위군" },
    { key: 13, label: "봉화군" },
    { key: 14, label: "성주군" },
    { key: 15, label: "영덕군" },
    { key: 16, label: "영양군" },
    { key: 17, label: "예천군" },
    { key: 18, label: "울릉군" },
    { key: 19, label: "울진군" },
    { key: 20, label: "의성군" },
    { key: 21, label: "청도군" },
    { key: 22, label: "청송군" },
    { key: 23, label: "칠곡군" }
  ],
  [
    { key: 0, section: true, label: "경상남도" },
    { key: 1, label: "거제시" },
    { key: 2, label: "김해시" },
    { key: 3, label: "밀양시" },
    { key: 4, label: "사천시" },
    { key: 5, label: "양산시" },
    { key: 6, label: "진주시" },
    { key: 7, label: "창원시" },
    { key: 8, label: "통영시" },
    { key: 9, label: "거창군" },
    { key: 10, label: "고성군" },
    { key: 11, label: "남해군" },
    { key: 12, label: "산청군" },
    { key: 13, label: "의령군" },
    { key: 14, label: "창녕군" },
    { key: 15, label: "하동군" },
    { key: 16, label: "함안군" },
    { key: 17, label: "함양군" },
    { key: 18, label: "합천군" }
  ],
  [{ key: 0, label: "제주특별자치도" }]
];
